### ISSUE TITLE
Validation package 'readConfig()' function ignores config 'settings'

### ISSUE THREAD

**Issue by f1ames** [kubeshop/monokle-core#435]
Reading config file like:

```yaml
plugins:
  yaml-syntax: false
  open-policy-agent: false
  kubernetes-schema: true
  pod-security-standards: true
settings:
  kubernetes-schema:
    schemaVersion: v1.27.1
```

results in `settings` being completely ignored.

This seems to be related to a fact that we have incomplete Zod schema there:

https://github.com/kubeshop/monokle-core/blob/ca88d491ad3b730ef32a5debd7b1601ab75a52f3/packages/validation/src/config/parse.ts#L25-L43
