### ISSUE TITLE
Add "extends" presets to validation configuration

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle-core#45]
I thought I was having a bug in our web application, but it was actually correct behaviour.

I had the following configuration file and was surprised that all rules were on. Now this is actually correct because by default SARIF rules are enabled (see [spec](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541290)). When I was writing this config I expected more a whitelist instead of blacklist approach - but both are valid options and blacklisting makes it even easier to discover all possible rules.

ESLint has the concept of extending rules. We could explore something similar where you have "default:none" (default is disable all), "default:all" (default is enable all) and "default:recommended" (default is as chosen by the plugin itself) presets where you can start from. Without an extends you would work with "default:recommended" which is the current behaviour (yet all rules actually are just enabled so it will seem as if it were default:all but we can tweak these defaults as we want). Later extends could also be replaced with some rulesets given by the community (similar to the famous eslint-config-airbnb).

Extends should maybe also have a few presets available.

```
extends:
  - "default:none"
plugins:
  yaml-syntax: true
  kubernetes-schema: true
  resource-links: true
  open-policy-agent: true
  labels: false
rules:
  yaml-syntax/no-bad-alias: "warn"
  yaml-syntax/no-bad-directive: false
  open-policy-agent/no-last-image: "err"
  open-policy-agent/cpu-limit: "err"
  open-policy-agent/memory-limit: "err"
  open-policy-agent/memory-request: "err"
  open-policy-agent/no-latest-image: "err"
settings:
  kubernetes-schema:
    schemaVersion: v1.24.2
```
